{
 "title": "Lodestar - networking",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Peers by client implementation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "lodestar_peers_by_client_count", "legendFormat": "{{client}}" }
     ]
    },
    {
     "title": "Mesh peers count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_type_count{type!~\"beacon_attestation\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Peer count per gossip score threshold",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "lodestar_gossip_peer_score_by_threshold_count",
       "legendFormat": "{{threshold}}"
      }
     ]
    },
    {
     "title": "Gossip score avg / min / max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "lodestar_gossip_score_avg_min_max_max",
       "legendFormat": "max"
      },
      {
       "expr": "lodestar_gossip_score_avg_min_max_avg",
       "legendFormat": "avg"
      },
      {
       "expr": "lodestar_gossip_score_avg_min_max_min",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Attnet mesh peers per subnet",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_beacon_attestation_subnet_count",
       "legendFormat": "{{subnet}}"
      }
     ]
    },
    {
     "title": "Mesh peers",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_type_count{type!~\"beacon_attestation\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Attnet count with > 0 mesh peers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "count(lodestar_gossip_mesh_peers_by_beacon_attestation_subnet_count > 0)",
       "legendFormat": "{{subnet}}"
      }
     ]
    },
    {
     "title": "Topic peers count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "lodestar_gossip_topic_peers_by_type_count{type!~\"beacon_attestation\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Network Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Network worker - latency to re-emit network event across worker boundary",
   "type": "timeseries",
   "description": "Async time to emit a network event across thread",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(network_worker_wire_events_on_worker_thread_event_latency[6m])",
     "legendFormat": "to worker thread"
    },
    {
     "expr": "rate(lodestar_network_worker_wire_events_on_main_thread_event_latency[6m])",
     "legendFormat": "to main thread"
    }
   ]
  },
  {
   "title": "Network worker - to/from worker port latency",
   "type": "timeseries",
   "description": "Async time to send a message across the worker/parent port",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(network_worker_wire_events_on_worker_thread_port_latency[6m])",
     "legendFormat": "to worker thread"
    },
    {
     "expr": "rate(lodestar_network_worker_wire_events_on_main_thread_port_latency[6m])",
     "legendFormat": "to main thread"
    }
   ]
  },
  {
   "title": "Peer stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Goodbyes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_peer_goodbye_received_total[$rate_interval])>0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Peer bad behaviour reports by reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_peers_report_peer_count[$rate_interval]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Goodbyes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_peer_goodbye_sent_total[$rate_interval])>0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Long lived attnets per peer",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "lodestar_peer_long_lived_attnets_count_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Goodbye reason for peer disconnecting after 1 day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_peer_long_connection_disconnect_total[$rate_interval]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Peer connection length",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "lodestar_peer_connection_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Score (app level, not gossip)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "lodestar_app_peer_score_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Peer connected / disconnect event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_peer_connected_total[$rate_interval])>0",
     "legendFormat": "connected_{{direction}}"
    },
    {
     "expr": "rate(lodestar_peer_disconnected_total[$rate_interval])>0",
     "legendFormat": "disconnect_{{direction}}"
    }
   ]
  },
  {
   "title": "Peer manager heartbeat duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_peer_manager_heartbeat_duration_seconds_sum[$rate_interval])\n/\nrate(lodestar_peer_manager_heartbeat_duration_seconds_count[$rate_interval])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Peer connect events offset (must be 0-1)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_peer_connected_total - lodestar_peer_disconnected_total - lodestar_peers_by_direction_count",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Peer requests to discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requested peers to connect and disconnect (rate / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*rate(lodestar_peers_requested_total_to_connect[$rate_interval])",
     "legendFormat": "to connect"
    },
    {
     "expr": "60*rate(lodestar_peers_requested_total_to_disconnect[$rate_interval])",
     "legendFormat": "to disconnect {{reason}}"
    }
   ]
  },
  {
   "title": "Requested subnets to query (rate / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*rate(lodestar_peers_requested_total_subnets_to_query[$rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requested total peers in subnets (rate / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60*rate(lodestar_peers_requested_total_subnets_peers_count[$rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Gossip validation queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gossip validation queue - Utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_queue_job_time_seconds_sum[$rate_interval])\n> 0.1/100",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queue - Processed jobs / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_gossip_validation_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queues - Job time (async)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_queue_job_time_seconds_sum[$rate_interval])\n/\nrate(lodestar_gossip_validation_queue_job_time_seconds_count[$rate_interval])\n> 10/1000",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queue - Dropped jobs %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_queue_dropped_jobs_total[$rate_interval])/(rate(lodestar_gossip_validation_queue_job_time_seconds_count[$rate_interval])+rate(lodestar_gossip_validation_queue_dropped_jobs_total[$rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queues - Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(lodestar_gossip_validation_queue_length[$rate_interval]) > 1",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queues - Job wait time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_queue_job_wait_time_seconds_sum[$rate_interval])\n/\nrate(lodestar_gossip_validation_queue_job_wait_time_seconds_count[$rate_interval])\n> 1.2/1000",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip Block process time",
   "type": "timeseries",
   "description": "Time elapsed between block slot time and the time block received via gossip",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  rate(lodestar_gossip_block_elapsed_time_till_processed_sum[$rate_interval])\n  -\n  rate(lodestar_gossip_block_elapsed_time_till_received_sum[$rate_interval])\n)\n/\nrate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval])",
     "legendFormat": "processed minus received"
    },
    {
     "expr": "rate(lodestar_execution_engine_http_client_request_time_seconds_sum{routeId=\"notifyNewPayload\"} [$rate_interval])\n/\nrate(lodestar_execution_engine_http_client_request_time_seconds_count{routeId=\"notifyNewPayload\"} [$rate_interval])",
     "legendFormat": "notifyNewPayload roundtrip"
    }
   ]
  },
  {
   "title": "Gossip Block Received Delay",
   "type": "timeseries",
   "description": "Time elapsed between block slot time and the time block received via gossip",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_received_sum[$rate_interval])\n/\nrate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval])",
     "legendFormat": "till received"
    },
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_processed_sum[$rate_interval])\n/\nrate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval])",
     "legendFormat": "till processed"
    },
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_become_head_sum[$rate_interval])\n/\nrate(lodestar_gossip_block_elapsed_time_till_become_head_count[$rate_interval])",
     "legendFormat": "till become head"
    }
   ]
  },
  { "title": "Network processor queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Processor execute work calls result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "rate(lodestar_network_processor_execute_work_calls_total[$rate_interval])",
     "legendFormat": "execute calls"
    },
    {
     "expr": "rate(lodestar_network_processor_can_not_accept_work_total[$rate_interval])",
     "legendFormat": "cannot accept work"
    },
    {
     "expr": "rate(lodestar_network_processor_execute_jobs_submitted_total_count[$rate_interval])",
     "legendFormat": "Jobs submitted"
    }
   ]
  },
  {
   "title": "Processor dependant regen queue % full",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "lodestar_regen_queue_length / 16",
     "legendFormat": "regen queue length"
    }
   ]
  },
  {
   "title": "Processor dependant bls thread pool queue % full",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "lodestar_bls_thread_pool_queue_length / 512",
     "legendFormat": "bls thread pool queue length"
    }
   ]
  },
  {
   "title": "Network processor executor jobs submitted per call",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rate(lodestar_network_processor_execute_jobs_submitted_total_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processor dependant bls thread workers busy % full",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "lodestar_bls_thread_pool_workers_busy\n/ on(instance)\ncount(lodestar_bls_thread_pool_time_seconds_sum) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "lodestar_gossip_validation_queue_current_drop_ratio",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Queue Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "lodestar_gossip_validation_queue_concurrency",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Gossip Attestation Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Errors Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_error_total{topic=\"beacon_attestation\"}[$rate_interval]) * 12",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Seen AttestatioDatas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lodestar_seen_cache_attestation_data_per_slot_total",
     "legendFormat": "Per Slot"
    },
    {
     "expr": "rate(lodestar_seen_cache_attestation_data_hit_total[$rate_interval])\n/ (\n    rate(lodestar_seen_cache_attestation_data_hit_total[$rate_interval]) +\n    rate(lodestar_seen_cache_attestation_data_miss_total[$rate_interval])\n)",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Reprocess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "lodestar_reprocess_gossip_attestations_per_slot_total",
     "legendFormat": "Per Slot"
    },
    {
     "expr": "rate(lodestar_reprocess_gossip_attestations_total[$rate_interval]) * 12",
     "legendFormat": "Avg Per Slot"
    }
   ]
  },
  {
   "title": "Seen AttestationDatas - Rejects Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "rate(lodestar_seen_cache_attestation_data_reject_total[$rate_interval]) * 12",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Reprocess - Resolved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "rate(lodestar_reprocess_gossip_attestations_resolve_total[$rate_interval]) * 12",
     "legendFormat": "Per Slot"
    },
    {
     "expr": "lodestar_reprocess_gossip_attestations_wait_time_resolve_seconds",
     "legendFormat": "Wait Sec"
    }
   ]
  },
  {
   "title": "Reprocess - Reject",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "targets": [
    {
     "expr": "rate(lodestar_reprocess_gossip_attestations_reject_total[$rate_interval]) * 12",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "lodestar_reprocess_gossip_attestations_wait_time_reject_seconds",
     "legendFormat": "Wait Sec"
    }
   ]
  },
  { "title": "Gossip Block Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_processed_bucket{le=\"0.5\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval]))",
     "legendFormat": "<=0.5s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_processed_bucket{le=\"1\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval]))",
     "legendFormat": "<=1s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_processed_bucket{le=\"2\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval]))",
     "legendFormat": "<=2s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_processed_bucket{le=\"4\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval]))",
     "legendFormat": "<=4s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_processed_bucket{le=\"6\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval]))",
     "legendFormat": "<=6s"
    }
   ]
  },
  {
   "title": "Received Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_received_bucket{le=\"0.5\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=0.5s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_received_bucket{le=\"1\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=1s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_received_bucket{le=\"2\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=2s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_received_bucket{le=\"4\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=4s"
    },
    {
     "expr": "sum(rate(lodestar_gossip_block_elapsed_time_till_received_bucket{le=\"6\"}[$rate_interval]))\n/\nsum(rate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=6s"
    }
   ]
  },
  {
   "title": "Process Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_process_block_errors[$rate_interval]) * 12",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Validation Errors Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_error_total{topic=\"beacon_block\"}[$rate_interval]) * 12",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "ReqResp metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_incoming_requests_total[$rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Outgoing requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_outgoing_requests_total[$rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Incoming requests error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_incoming_requests_error_total[$rate_interval])/(rate(beacon_reqresp_incoming_requests_total[$rate_interval])>0)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Outgoing requests error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_outgoing_requests_error_total[$rate_interval])/(rate(beacon_reqresp_outgoing_requests_total[$rate_interval]) > 0)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Incoming request handler time > 5 sec (req / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "60 * (\n    rate(beacon_reqresp_incoming_request_handler_time_seconds_count [$rate_interval])\n    - on(method)\n    rate(beacon_reqresp_incoming_request_handler_time_seconds_bucket{le=\"5\"} [$rate_interval])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Outgoing request roundtrip time > 5 sec (req / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "60 * (\n    rate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_count [$rate_interval])\n    - on(method)\n    rate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_bucket{le=\"5\"} [$rate_interval])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Incoming request handler time avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_incoming_request_handler_time_seconds_sum[$rate_interval])\n/\nrate(beacon_reqresp_incoming_request_handler_time_seconds_count[$rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Outgoing request roundtrip time avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_sum[$rate_interval])\n/\nrate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_count[$rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Dial errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_dial_errors_total[$rate_interval])"
    }
   ]
  },
  {
   "title": "Rate limiter errors / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_rate_limiter_errors_total[$rate_interval])",
     "legendFormat": "{{tracker}}"
    }
   ]
  }
 ]
}